[0;33m--- esp-idf-monitor 1.3.1 on /dev/ttyACM0 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x40378342: esp_cpu_wait_for_intr at /home/hevwp4b/esp/esp-idf/components/esp_hw_support/cpu.c:145
[0m
[0;33m0x403751d4: call_start_cpu1 at /home/hevwp4b/esp/esp-idf/components/esp_system/port/cpu_start.c:178
[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0mException in thread Thread-2:
Traceback (most recent call last):
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/esp_idf_monitor/base/serial_reader.py", line 76, in run
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/esp_idf_monitor/base/serial_reader.py", line 83, in run
    self.close_serial()
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/esp_idf_monitor/base/serial_reader.py", line 104, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/esp_idf_monitor/base/serial_reader.py", line 119, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/esp_idf_monitor/base/serial_reader.py", line 100, in run
    self.close_serial()
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/esp_idf_monitor/base/serial_reader.py", line 104, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/hevwp4b/.espressif/python_env/idf5.2_py3.8_env/lib/python3.8/site-packages/esp_idf_monitor/base/serial_reader.py", line 119, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
OSError: [Errno 5] Input/output error
[0m
